### ISSUE TITLE
SSO bugs out sometimes on IE

### ISSUE THREAD

**Issue by striedinger** [coralproject/talk#1956]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:
Click on Sign in with (Google/Facebook), and successfully log in after external log in.

#### Actual outcome:
Successfully authenticate with external provider, popup closes, but no login in Talk. Login button still available and when trying to login using any method none will work.

#### How to reproduce the issue:
- Log in using external provider
- Immediately log out.
(Here it gets tricky as I have not found the exact steps that cause the bug)
Either:
- Log in, refresh page while logged in, log out and try to log in.
- Log in, log out, refresh page, try to log back in.
- Log in, open page in another browser (Chrome) and log in, close other browser tab, Log out from IE, try to log back in.
- Log in, log out, open page in another browser (Chrome) and log in, try to log back in.

I am sorry I can't be more specific but it is not as recurring, but when it happens I would say it is a breaking bug as it messes the whole system. The only way I have found out to make it work again is close the browser itself and open back the page to log in again.

#### Version and environment
Talk 4.5 on IE11

**Comment by wyattjoh** [comment]
Are you currently using any non-required configuration for your instance? We just released some fixes related to social sign on in [4.6.4](https://github.com/coralproject/talk/releases/tag/v4.6.4) when using [TALK_STATIC_URI](https://docs.coralproject.net/talk/advanced-configuration/#talk-static-uri).

**Comment by striedinger** [comment]
@wyattjoh only customization we are doing is enabling google and facebook auth plugins with a docker on build file. Although we are using 4.5. Will try to upgrade to 4.6.4 in the AM and come back with results.

**Comment by striedinger** [comment]
@wyattjoh I upgraded to 4.6.4 and bug is still happening. I definitely consider this a bug since my instance is up and running perfectly with no issues whatsoever. It's just on a rare occurrence that when doing those steps provided it bugs out on IE and login with OAuth messes up.

**Comment by wyattjoh** [comment]
I've just attempted to perform the testing you suggested on IE 11 against our blog (running at https://coralproject.net/blog/happy-hacktoberfest/) and I can't seem to reproduce the error you described. If you can reproduce but provide any console logs that occurred, that would be helpful in ensuring that we have the best picture of the problem.

**Comment by striedinger** [comment]
@wyattjoh I just got it on your blog. I havent found a way to keep developer tools open on IE11 after window (popup in this case) closes. But I pretty much did the same thing. Log in, log out, refresh page, try to log in again or log in, refresh, log out and try to log back in. Eventually it bugs out and prevents any type of logging in to happen.

**Comment by wyattjoh** [comment]
Do you have any browser plugins installed? Any non-standard testing?

I just ran through your steps about 5 times on Browserstack Windows 10 IE11 without any issues so far.

**Comment by striedinger** [comment]
Clean browser. Nothing out of the ordinary apart from doing what I mentioned. I am going to try to record it and will back to post it when I have it.

**Comment by striedinger** [comment]
![talk_bug](https://user-images.githubusercontent.com/6549408/46435386-3d89ef00-c724-11e8-9d9d-9c9fb3c6c9a9.gif)
@wyattjoh  - Like I mentioned earlier, it's a pretty damn difficult bug to reproduce. But when it does happen, and sometimes it happens even easier, it is breaking as it completely disables login. I would imagine a non-tech person would be frustrated if this were to happen and just give up on commenting.

**Comment by wyattjoh** [comment]
Do you think you could open the console on the blog page to see if anything is being posted there?

**Comment by striedinger** [comment]
@wyattjoh Nothing pops up in console on the blog page. It's very easy to reproduce when following those steps, it eventually will bug out.

**Comment by kgardnr** [comment]
Hey @striedinger SSO is improved for v5, but we are also not supporting IE11 for v5. We'd love for you to check it out, you can see it currently in the `next` branch, and an RC release is forthcoming in September! Gonna close this one out for now 🎉
