### ISSUE TITLE
Add missing Polish translations

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#2856]
There are some English strings still here for the stream translations: https://github.com/coralproject/talk/blob/master/src/locales/pl/stream.ftl

**Comment by kgardnr** [comment]
@janslu  there are some missing translations - do you want to take a look?

**Comment by janslu** [comment]
This was fixed in #2853, sorry about that. I used a previous checkout. 

As a notice - the original English version of https://github.com/coralproject/talk/blob/master/src/locales/en-US/stream.ftl seem to have the same key in lines 333 and 334  - profile-account-notifications-emailNotifications.

**Comment by kgardnr** [comment]
Hey @janslu I think it's still missing translations in that stream file, can you double check? I see mixed English and Polish there, for example:

```comments-bannedInfo-violatedCommunityGuidelines =
  Someone with access to your account has violated our community
  guidelines. As a result, your account has been banned. You will no
  longer be able to comment, respect or report comments. If you think
  this has been done in error, please contact our community team.
```

**Comment by janslu** [comment]
@kgardnr Thank you for pointing this one out. I don't know how I missed it. I will do my best to triple check future updates, really sorry about this. 

Is this something that can wait for QA translations? I have pushed a small suggestion for translation key change on one of the tabs and I think it will be best to wait until the missing key is added to English before I push my working copy with QA translation. In the meantime I'm also working on shortening some phrases - polish words are often longer and some important UI elements land off-screen on narrower mobiles (namely report comment button). I'm still working on this.
